In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(np.shape(a))

(3,)


In [5]:
b = np.array([[1,2], [3,4]])

In [6]:
print(b)

[[1 2]
 [3 4]]


In [7]:
print(np.shape(b))

(2, 2)


In [8]:
# accessing value 3 from array b through array indexing

b[1,0]

3

In [9]:
c = np.zeros((3,2))

In [10]:
c

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
d = np.ones((3,2))

In [12]:
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
e = np.full((3,3), 6)
e

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [15]:
f = np.random.random((3,4))
f

array([[0.04843148, 0.12358993, 0.95704602, 0.14549304],
       [0.85347068, 0.16487823, 0.40027118, 0.17618884],
       [0.22451448, 0.07681359, 0.60258204, 0.13976132]])

In [22]:
h = np.array([[1,2,3,4 ], [5,6,7,8], [9,10,11,12]])
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
# accesing 2,3,6,7 from h through array indexing

h = h[:2, 1:3]

print(h)

[[2 3]
 [6 7]]


In [25]:
h = np.array([[1,2,3,4 ], [5,6,7,8], [9,10,11,12]])
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
i = h[:2, 1:3]

In [28]:
i

array([[2, 3],
       [6, 7]])

In [29]:
i[0,0] = 500
print(i)

[[500   3]
 [  6   7]]


In [30]:
print(h)

[[  1 500   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [36]:
j = np.array([1,2])

print(j.dtype)

k = np.array([1.0,2.0])
print(k.dtype)

l= np.array([1.0,2.0], dtype = np.int32)
l= np.array([1.0,2.0], dtype = np.int64)
print(l.dtype)

int32
float64
int64


In [40]:
x = np.array([[1,2], [3,4]], dtype = np.float16)
y = np.array([[5,6], [7,8]], dtype = np.float16)
print(x)
print(y)
print(x+y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]


In [39]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [41]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [42]:
print(x/y)

[[0.2    0.3333]
 [0.4285 0.5   ]]


In [43]:
print(np.sqrt(x))

[[1.    1.414]
 [1.732 2.   ]]


In [44]:
print(np.sqrt(y))

[[2.236 2.45 ]
 [2.646 2.828]]


In [45]:
np.sum(x)

10.0

In [46]:
np.sum(x, axis=1)

array([3., 7.], dtype=float16)

In [47]:
np.sum(x, axis=0)

array([4., 6.], dtype=float16)